apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html  # Mount the PVC into Nginx's HTML directory
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc  # Reference the PVC
