apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner   # No automatic provisioning
volumeBindingMode: WaitForFirstConsumer     # Wait for pod to be scheduled before binding PV
reclaimPolicy: Retain
allowVolumeExpansion: false
