apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi  # Define the size of the volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # This allows the volume to be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # When the PVC is deleted, retain the volume
  local:
    path: /mnt/data/nginx  # The local path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <node-name>  # Replace with the specific node name, or use a label selector
