apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-azure
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS  # Managed Disk type (e.g., Standard_LRS, Premium_LRS)
  kind: Managed  # Use managed disks
  fsType: ext4   # Filesystem type
reclaimPolicy: Delete
allowVolumeExpansion: true
