apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html # Path inside the container
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
