apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi # Size of the volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # This volume can only be mounted by a single node at a time
  persistentVolumeReclaimPolicy: Retain # Keeps the PV after PVC deletion
  storageClassName: manual # Storage class for PV
  hostPath:
    path: /mnt/data/nginx # Path on the host system
    type: DirectoryOrCreate # Creates the directory if it doesn't exist
